#ifndef STATUS_H
#define STATUS_H

typedef enum STATUS_T
{
    FAILED,
    SUCCESS,
    STRING_TOO_LONG,
    POINTER_IS_NULL,
    OUT_OF_SPACE,
    DUPLICATE,
    AD_CAPACITY_REACHED,
    COMPANY_NOT_FOUND
}STATUS_T;

#endif